// ─────────────────────────────────────────────────────────
// firebase_options.dart
// Generated by: flutterfire configure
// Replace ALL placeholder values below with your real
// Firebase project config from the Firebase Console.
// ─────────────────────────────────────────────────────────
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Replace with your Firebase project values ──────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'AIzaSyBwfmgyVp_mCtOmn_lu7sLzuWcoPKCLekQ',
    appId:             '1:131387462669:web:cc5067c3bab6b1fc127144',
    messagingSenderId: '131387462669',
    projectId:         'evexia-91ecf',
    authDomain:        'evexia-91ecf.firebaseapp.com',
    storageBucket:     'evexia-91ecf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyBwfmgyVp_mCtOmn_lu7sLzuWcoPKCLekQ',
    appId:             '1:131387462669:android:24ec22bd1126ed26127144',
    messagingSenderId: '131387462669',
    projectId:         'evexia-91ecf',
    storageBucket:     'evexia-91ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'AIzaSyCMXBELHtGKOPu6cTtcN0OWkFgpNoQlIhw',
    appId:             '1:131387462669:ios:e2c74e7bae4ec628127144',
    messagingSenderId: '131387462669',
    projectId:         'evexia-91ecf',
    storageBucket:     'evexia-91ecf.firebasestorage.app',
    iosClientId:       '131387462669-54bi3221cmll3hrv93u7usj30kmj0kr6.apps.googleusercontent.com',
    iosBundleId:       'com.example.evexiaWellbeingApp',
  );
}
