// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwfmgyVp_mCtOmn_lu7sLzuWcoPKCLekQ',
    appId: '1:131387462669:web:370c8161abd75731127144',
    messagingSenderId: '131387462669',
    projectId: 'evexia-91ecf',
    authDomain: 'evexia-91ecf.firebaseapp.com',
    storageBucket: 'evexia-91ecf.firebasestorage.app',
    measurementId: 'G-7CL6L9H9LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbVHSRkCP_5ut_dyBthUhtqvd6lEJPdYM',
    appId: '1:131387462669:android:24ec22bd1126ed26127144',
    messagingSenderId: '131387462669',
    projectId: 'evexia-91ecf',
    storageBucket: 'evexia-91ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMXBELHtGKOPu6cTtcN0OWkFgpNoQlIhw',
    appId: '1:131387462669:ios:e2c74e7bae4ec628127144',
    messagingSenderId: '131387462669',
    projectId: 'evexia-91ecf',
    storageBucket: 'evexia-91ecf.firebasestorage.app',
    iosBundleId: 'com.example.evexiaWellbeingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMXBELHtGKOPu6cTtcN0OWkFgpNoQlIhw',
    appId: '1:131387462669:ios:e2c74e7bae4ec628127144',
    messagingSenderId: '131387462669',
    projectId: 'evexia-91ecf',
    storageBucket: 'evexia-91ecf.firebasestorage.app',
    iosBundleId: 'com.example.evexiaWellbeingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwfmgyVp_mCtOmn_lu7sLzuWcoPKCLekQ',
    appId: '1:131387462669:web:230ead467dd36bbd127144',
    messagingSenderId: '131387462669',
    projectId: 'evexia-91ecf',
    authDomain: 'evexia-91ecf.firebaseapp.com',
    storageBucket: 'evexia-91ecf.firebasestorage.app',
    measurementId: 'G-85FVWB2JHL',
  );
}
